# Configuration file for gptgodmc
# Make sure you update this before running!

# google gemini api key for main and secondary llm
# the plugin won't work without this
# https://aistudio.google.com/
geminiKey: ""

# for tts. Get key from https://console.sws.speechify.com/api-keys
speechify-key: ""

# language in ISO-639 format https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
language: en

# if set to true:
# - When players die they are put in spectator mode
# - When everyone dies the map is reset
# This is the intended way to play
# only set to false for testing and debugging
Rounds: true

# the world the server will load on starting
# worlds are stored in plugins/gptgodmc/worlds
# if empty or invalid the Round System won't work
startingWorld: "island"

# gemini main model name
# use gemini-1.5-flash for more rapid and cheaper responses
# or use gemini-1.5-pro for more context and brains
model-name: gemini-1.5-flash

# secondary model (for transcriptions and command gen)
# recomended models gemini-1.5-flash or the new gemini-1.5-flash-8b
secondary-model-name: gemini-1.5-flash-8b

# Gemini Model tempurature
# turn up the heat
# 1.0 or below is more behaved, above is more creative
model-tempurature: 1.6

# Gemini model token limit
# flash can have up to 1mil and pro up to 2mil
gpt-model-token-limit: 1000000

# token limit for secondary model
gpt-secondary-token-limit: 1000000

# whether or not the mod will make calls to Gemini
enabled: true

# The gamemode, here are the current options:
# this is case sensitive
#[SANDBOX, DEATHMATCH]
gamemode: SANDBOX

# The potential behaviors to be given to Gemini. A specified amount will be chosen to either be liked, or disliked.
potentialBehaviors:
  [
    "killing animals",
    "fighting other players",
    "slaying monsters",
    "using hostile language",
    "using vulgar language",
    "using friendly language",
    "building structures of worship",
    "building non-religious structures",
    "materialistic wants",
    "helping other players",
    "connecting with animals",
    "growing plants",
    "using fire and explosions",
    "love between players",
    "sexual behaviour",
    "generosity",
    "ritual sacrifice",
    "eating meat",
  ]

# X behaviors will be selected as disliked/liked.
# A behavior cannot be both liked and disliked, nor can there be duplicates.
# The total required behaviors must be equal to or less than the amount of potential behaviors.

likedBehaviors: 3
dislikedBehaviors: 3

# How long the objectives given by GPT last
# (in minutes)
objectiveDecay: 6

# the amount of time that will pass between calls to Gemini (in seconds)
# keep in mind that gemini-pro free tier has a rate limit of 2 calls per min
# so with forced actions enabled you must have this more than 60
# can't be less that 1 second
# AI may get pushy at lower than 20
# if forced actons is enabled (double calls to api per run)
# default: 30
rate: 30

# the amount of time that will pass between calls to transcribe voice chats
# stops flickering microphones from spamming the api
# and allows you to control how much spending you want for transcription
# uses the secondary model for transcriptions
transcription-rate: 20

# use AI Text to Speech voice for god (uses OpenAI and will cost a bit more money)
tts: true

# The voice used by the speechify TTS
# default: benjamin
speechify-voice: benjamin

# The Speechify audio model to use [simba-english, simba-base, simba-multilingual, simba-turbo]
# default: simba-multilingual
speechify-model: simba-multilingual

# write your own game-mode prompt here instead of the deafault game-mode prompt
promptOverride: ""

# Optional: override specific prompt blocks used by the AI god. Leave commented or blank to use defaults.
prompts:
  gamemode:
    SANDBOX: ""
    DEATHMATCH: ""
  base:
    PROMPT_BASE: ""
    REQUIREMENTS: ""
    GUIDANCE: ""
    STYLE: ""
    ESCALATION: ""
    ROLEPLAY: ""
  summarize:
    CONTEXT: ""
  transcription:
    MANY_CONTEXT: ""
    SINGLE_CONTEXT: ""
# old gpt configurations

# your OpenAi API key from https://platform.openai.com/api-keys
# if openai chatgpt is enabled
# openAiKey: ""
# name of the gpt model to use (in the case that gpt is enabled)
# can be found here: https://openai.com/api/pricing/
# gpt-model-name: gpt-4o
# The voice used by the TTS
# https://platform.openai.com/docs/guides/text-to-speech/voice-options
#voice: onyx
